# Generated by Django 4.2.5 on 2024-01-02 08:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastTimeUpdation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemNo', models.CharField(blank=True, max_length=500, null=True)),
                ('qnty', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=2000, null=True)),
                ('Description2', models.CharField(blank=True, max_length=2000, null=True)),
                ('SearchDescription', models.CharField(blank=True, max_length=2000, null=True)),
                ('LotSize', models.IntegerField(blank=True, null=True)),
                ('Blocked', models.CharField(blank=True, max_length=500, null=True)),
                ('CompoundNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('Material', models.CharField(blank=True, max_length=500, null=True)),
                ('Durometer', models.CharField(blank=True, max_length=500, null=True)),
                ('DurometerScale', models.CharField(blank=True, max_length=500, null=True)),
                ('DurometerRange', models.CharField(blank=True, max_length=500, null=True)),
                ('Color', models.CharField(blank=True, max_length=500, null=True)),
                ('LowTemperature', models.IntegerField(blank=True, null=True)),
                ('HighTemperature', models.FloatField(blank=True, null=True)),
                ('FDACompliant', models.CharField(blank=True, max_length=500, null=True)),
                ('MaterialSubtype', models.CharField(blank=True, max_length=500, null=True)),
                ('CureType', models.CharField(blank=True, max_length=500, null=True)),
                ('Encapsulated', models.CharField(blank=True, max_length=500, null=True)),
                ('Brand', models.CharField(blank=True, max_length=500, null=True)),
                ('SalesNotes', models.TextField(blank=True, null=True)),
                ('MaterialNotes', models.TextField(blank=True, null=True)),
                ('CleanRoomManufactured', models.CharField(blank=True, max_length=500, null=True)),
                ('FDAType', models.CharField(blank=True, max_length=500, null=True)),
                ('USPClassVI', models.CharField(blank=True, max_length=500, null=True)),
                ('USPClassVI87', models.CharField(blank=True, max_length=500, null=True)),
                ('USPClassVI88', models.CharField(blank=True, max_length=500, null=True)),
                ('A3Sanitary', models.CharField(blank=True, max_length=500, null=True)),
                ('KTW', models.CharField(blank=True, max_length=500, null=True)),
                ('WRAS', models.CharField(blank=True, max_length=500, null=True)),
                ('ULListed', models.CharField(blank=True, max_length=500, null=True)),
                ('ULRating', models.CharField(blank=True, max_length=500, null=True)),
                ('MetalDetectable', models.CharField(blank=True, max_length=500, null=True)),
                ('NSF61', models.CharField(blank=True, max_length=500, null=True)),
                ('NSF51', models.CharField(blank=True, max_length=500, null=True)),
                ('AntiExplosiveDecompression', models.CharField(blank=True, max_length=500, null=True)),
                ('NACETM0297', models.CharField(blank=True, max_length=500, null=True)),
                ('NORSOKM710', models.CharField(blank=True, max_length=500, null=True)),
                ('UltraLowTemperature', models.CharField(blank=True, max_length=500, null=True)),
                ('UltraHighTemperature', models.CharField(blank=True, max_length=500, null=True)),
                ('SteamResistant', models.CharField(blank=True, max_length=500, null=True)),
                ('UltraSteamResistant', models.CharField(blank=True, max_length=500, null=True)),
                ('InternallyLubricated', models.CharField(blank=True, max_length=500, null=True)),
                ('ExternallyLubricated', models.CharField(blank=True, max_length=500, null=True)),
                ('ConductiveFiller', models.CharField(blank=True, max_length=500, null=True)),
                ('LowCompressionSet', models.CharField(blank=True, max_length=500, null=True)),
                ('CrossSectionalGeometry', models.CharField(blank=True, max_length=500, null=True)),
                ('CrossSectionalDiameter', models.CharField(blank=True, max_length=500, null=True)),
                ('InsideDiameter', models.CharField(blank=True, max_length=500, null=True)),
                ('SizeAS568', models.CharField(blank=True, max_length=500, null=True)),
                ('SizeJIS', models.CharField(blank=True, max_length=500, null=True)),
                ('SizeMetric', models.CharField(blank=True, max_length=500, null=True)),
                ('SizeStandard', models.CharField(blank=True, max_length=500, null=True)),
                ('Online', models.CharField(blank=True, max_length=105, null=True)),
                ('picture1', models.CharField(blank=True, max_length=1050, null=True)),
                ('picture2', models.CharField(blank=True, max_length=1050, null=True)),
            ],
        ),
    ]
